blueprint:
  name: Motion lights
  description: Turns off lights when motion is cleared
  domain: automation
  source_url: https://github.com/jonttu0/ha-blueprints/blob/main/motion_lights.yaml
  author: Jonttu
  input:
    only_at_night:
      name: Turn light on only at night
      description: When selected motion turns lights on only at night
      selector:
        boolean:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    turn_on_light:
      name: Lights to turn on
      selector:
        target:
          entity:
            domain: light
    turn_off_light:
      name: Light to turn off
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to wait after motion is cleared before lights turn off
      default: 60
      selector:
        number:
          min: 0
          max: 10800
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    to: "off"
    for:
      seconds: !input no_motion_wait
  - trigger: state
    entity_id: !input motion_entity
    to: "on"

actions:
  - if:
      - condition: state
        entity_id: !input motion_entity
        state: "on"
    then:
      - if:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ input.only_at_night }}"
                  - condition: state
                    entity_id: sun.sun
                    state: "below_horizon"
              - condition: template
                value_template: "{{ not input.only_at_night }}"
        then:
          - action: light.turn_on
            target: !input turn_on_light
    else:
      - action: light.turn_off
        target: !input turn_off_light
