blueprint:
  name: Philips Hue Dimmer Switch V2 (Z2M Events)
  description: Control lights using the modern Zigbee2MQTT Event entity.
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch
      description: Select the EVENT entity (e.g., event.my_switch_action).
      selector:
        entity:
          integration: mqtt
          domain: event
    on_press:
      name: 'On Button - Press'
      default: []
      selector:
        action: {}
    up_press:
      name: 'Up Button - Press'
      default: []
      selector:
        action: {}
    down_press:
      name: 'Down Button - Press'
      default: []
      selector:
        action: {}
    off_press:
      name: 'Off Button - Press'
      default: []
      selector:
        action: {}
    on_hold:
      name: 'On Button - Hold'
      default: []
      selector:
        action: {}
    off_hold:
      name: 'Off Button - Hold'
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote

action:
  - variables:
      command: "{{ trigger.to_state.attributes.event_type | default('') }}"
  - choose:
      # ON Button
      - conditions: "{{ command in ['on', 'on-press', 'on_press'] }}"
        sequence: !input on_press
      - conditions: "{{ command in ['on-hold', 'on_hold'] }}"
        sequence: !input on_hold

      # UP Button
      - conditions: "{{ command in ['up-press', 'up_press', 'brightness_move_up'] }}"
        sequence: !input up_press

      # DOWN Button
      - conditions: "{{ command in ['down-press', 'down_press', 'brightness_move_down'] }}"
        sequence: !input down_press

      # OFF Button
      - conditions: "{{ command in ['off', 'off-press', 'off_press'] }}"
        sequence: !input off_press
      - conditions: "{{ command in ['off-hold', 'off_hold'] }}"
        sequence: !input off_hold
