blueprint:
  name: Philips Hue Dimmer Switch V2 (Z2M Events)
  description: Control lights using the modern Zigbee2MQTT Event entity.
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch
      description: Select the EVENT entity (e.g., event.my_switch_action).
      selector:
        entity:
          integration: mqtt
          domain: event
    on_press:
      name: 'On Button - Press'
      default: []
      selector:
        action: {}
    up_press:
      name: 'Up Button - Press'
      default: []
      selector:
        action: {}
    down_press:
      name: 'Down Button - Press'
      default: []
      selector:
        action: {}
    off_press:
      name: 'Off Button - Press'
      default: []
      selector:
        action: {}
    on_hold:
      name: 'On Button - Hold'
      default: []
      selector:
        action: {}
    off_hold:
      name: 'Off Button - Hold'
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote

action:
  - variables:
      # For events, the button press is stored in the 'event_type' attribute
      command: "{{ trigger.to_state.attributes.event_type }}"
  - choose:
      # ON Button
      - conditions: "{{ command == 'on-press' }}"
        sequence: !input on_press
      - conditions: "{{ command == 'on-hold' }}"
        sequence: !input on_hold

      # UP Button
      - conditions: "{{ command == 'up-press' }}"
        sequence: !input up_press

      # DOWN Button
      - conditions: "{{ command == 'down-press' }}"
        sequence: !input down_press

      # OFF Button
      - conditions: "{{ command == 'off-press' }}"
        sequence: !input off_press
      - conditions: "{{ command == 'off-hold' }}"
        sequence: !input off_hold
